### ISSUE TITLE
Issue on page /notebooks/nighttime-lights/README.html

### ISSUE THREAD

**Issue by Jagbakpe** [datapartnership/gaza-israel-conflict-impact-analysis#60]
![image](https://github.com/datapartnership/gaza-israel-conflict-impact-analysis/assets/135717208/6e50d087-f539-4d0d-adf0-4c48c15bed60)

**Comment by g4brielvs** [comment]
@Jagbakpe Thanks for opening this issue. Your NASA token is confidential and must never be posted publicly. Please see also [this example](https://worldbank.github.io/template/notebooks/nasa-apod.html) on how to securely use secrets.

**Comment by Jagbakpe** [comment]
Thank you for your response, I thought so too, tried putting the token in quotations but still got the same error.

**Comment by Jagbakpe** [comment]
I would have sent a screenshot but my power is out at the moment…unfortunately.
